name: butter_cli
description: Generates the butter framework scaffolding.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  butter_cli:

dependencies:
  path: ^1.6.0
  args: ^1.6.0
  io: ^0.3.4
  mustache: ^1.1.1
  recase: ^3.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
